server:
  port: ${conference-partner.server.port}

logging:
  level:
    cn.edu.ecnu.conferencepartner: debug

spring:
  application:
    name: conference-partner
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${conference-partner.database.host}:${conference-partner.database.port}/conference_partner?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: ${conference-partner.database.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

springdoc:
  default-flat-param-object: true

conference-partner:
  jwt:
    secret-key: oW6nKZHzMePnDMOTxULx9Dg6Is8GIZ7EaaAneXGSqGo=
    time-to-live: 3600  # 令牌有效期，单位为秒
